using System.Diagnostics;
using System.Text.Json;
using Microsoft.Extensions.Options;
using TravelAgency.Application.DTOs.Travel;
using TravelAgency.Application.Providers;
using TravelAgency.Infrastructure.Database;
using TravelAgency.Infrastructure.Database.Entities;
using TravelAgency.Infrastructure.Options;

namespace TravelAgency.Infrastructure.Providers.Amadeus;

public sealed class AmadeusLocationProvider(IHttpClientFactory factory, AmadeusAuthClient auth, IOptions<AmadeusOptions> options, TravelDbContext db) : ILocationProvider
{ public async Task<IReadOnlyList<LocationSuggestionDto>> SearchLocationsAsync(string query, CancellationToken cancellationToken){var sw=Stopwatch.StartNew();var c=factory.CreateClient();c.DefaultRequestHeaders.Authorization=new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", await auth.GetAccessTokenAsync(cancellationToken)); var url=$"{options.Value.BaseUrl}/v1/reference-data/locations?subType=CITY,AIRPORT&keyword={Uri.EscapeDataString(query)}"; var res=await c.GetAsync(url,cancellationToken); var body=await res.Content.ReadAsStringAsync(cancellationToken); db.ProviderRequestLogs.Add(new ProviderRequestLogEntity{Id=Guid.NewGuid(),Provider="Amadeus",Endpoint="/v1/reference-data/locations",StatusCode=(int)res.StatusCode,Success=res.IsSuccessStatusCode,DurationMs=sw.ElapsedMilliseconds,CreatedAtUtc=DateTime.UtcNow}); await db.SaveChangesAsync(cancellationToken); if(!res.IsSuccessStatusCode) return []; var doc=JsonDocument.Parse(body); return doc.RootElement.GetProperty("data").EnumerateArray().Select(x=>new LocationSuggestionDto(x.GetProperty("iataCode").GetString()??"",x.GetProperty("name").GetString()??"",x.GetProperty("subType").GetString()??"",x.GetProperty("address").GetProperty("countryCode").GetString()??"",$"{x.GetProperty("name").GetString()} ({x.GetProperty("iataCode").GetString()})")).ToList(); }}

public sealed class AmadeusFlightProvider(IHttpClientFactory factory, AmadeusAuthClient auth, IOptions<AmadeusOptions> options, TravelDbContext db) : IFlightProvider
{ public async Task<IReadOnlyList<FlightOptionDto>> SearchFlightsAsync(TripSearchRequest request, CancellationToken cancellationToken){var sw=Stopwatch.StartNew();var c=factory.CreateClient();c.DefaultRequestHeaders.Authorization=new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", await auth.GetAccessTokenAsync(cancellationToken)); var q=$"originLocationCode={request.Origin}&destinationLocationCode={request.Destination}&departureDate={request.DepartureDate:yyyy-MM-dd}&adults={request.Adults}&currencyCode={request.Currency}&max={request.MaxFlightResults}"; if(request.ReturnDate is not null) q += $"&returnDate={request.ReturnDate:yyyy-MM-dd}"; var res=await c.GetAsync($"{options.Value.BaseUrl}/v2/shopping/flight-offers?{q}",cancellationToken); var body=await res.Content.ReadAsStringAsync(cancellationToken); db.ProviderRequestLogs.Add(new ProviderRequestLogEntity{Id=Guid.NewGuid(),Provider="Amadeus",Endpoint="/v2/shopping/flight-offers",StatusCode=(int)res.StatusCode,Success=res.IsSuccessStatusCode,DurationMs=sw.ElapsedMilliseconds,CreatedAtUtc=DateTime.UtcNow}); await db.SaveChangesAsync(cancellationToken); if(!res.IsSuccessStatusCode) throw new InvalidOperationException("Amadeus flights failed."); var doc=JsonDocument.Parse(body); return doc.RootElement.GetProperty("data").EnumerateArray().Select(o=>new FlightOptionDto{Provider="Amadeus",ProviderOfferId=o.GetProperty("id").GetString()??"",AirlineCode=o.GetProperty("validatingAirlineCodes")[0].GetString()??"",TotalPrice=new MoneyDto(decimal.Parse(o.GetProperty("price").GetProperty("total").GetString()??"0"),o.GetProperty("price").GetProperty("currency").GetString()??request.Currency),Duration=o.GetProperty("itineraries")[0].GetProperty("duration").GetString()??"",Stops=Math.Max(0,o.GetProperty("itineraries")[0].GetProperty("segments").GetArrayLength()-1)}).ToList(); }}
